"""add student model constraints and active index

Revision ID: 07a52dbd21ff
Revises: 348481398ed0
Create Date: 2026-08-22 23:14:21.038353
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "07a52dbd21ff"
down_revision = "348481398ed0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default="true",
        existing_nullable=False,
    )
    op.create_index("ix_students_department", "students", ["department"], unique=False)
    op.create_index("ix_students_is_active", "students", ["is_active"], unique=False)
    op.create_index("ix_students_semester", "students", ["semester"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_students_semester", table_name="students")
    op.drop_index("ix_students_is_active", table_name="students")
    op.drop_index("ix_students_department", table_name="students")
    op.alter_column(
        "students",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
