"""add attendance records

Revision ID: 646c91b491a6
Revises: 6aad65bb3b65
Create Date: 2026-08-23 23:17:53.595287
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "646c91b491a6"
down_revision = "6aad65bb3b65"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attendance_sessions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendance_sessions",
        sa.Column(
            "subject", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("start_time", postgresql.TIME(), autoincrement=False, nullable=False),
        sa.Column("end_time", postgresql.TIME(), autoincrement=False, nullable=False),
        sa.Column(
            "department", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("semester", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "section", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_sessions")),
    )
    # ### end Alembic commands ###
