"""add enrollments

Revision ID: 782c9033d1fc
Revises: 2f5f9d3a7c41
Create Date: 2026-08-31 20:00:07.361574
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "782c9033d1fc"
down_revision = "2f5f9d3a7c41"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "attendance_sessions", "course_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "attendance_sessions", "course_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###
